OralBAC/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main


app_name = 'OralBAC'
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', main, name='main'),
    path('texte/', include('Presentation.urls')),
]

Presentation/urls.py
from django.urls import path

from .views import index, texte, add_author


app_name = 'Presentation'
urlpatterns = [
    path('', index, name='index'),
    # path('ajouter/', add, name='add'),
    path('ajouter-auteur/', add_author, name='add_author'),
    path('<str:key>/', texte, name='texte'),
]

Presentation/models.py
from django.db import models
# from django.utils.crypto import get_random_string
import uuid

class Auteur(models.Model):
    name = models.CharField(max_length=50)
    birth_date = models.DateField("Birth Year")
    death_date = models.DateField("Year of Death")
    description = models.TextField()

    def __str__(self):
        return self.name


class Texte(models.Model):
    url = models.UUIDField(
            default=uuid.uuid4,
            unique=True,
            editable=False
        )
    title = models.CharField(max_length=50, blank=True)
    auteur = models.ForeignKey(Auteur, on_delete=models.CASCADE, null=True)
    presentation = models.TextField()
    problematique = models.CharField(max_length=500)
    texte_conclusion = models.TextField()
    ouverture = models.TextField()

    def __str__(self):
        return self.title


class Mouvement(models.Model):
    texte = models.ForeignKey(Texte, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=True)
    range = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return str(self.texte) + ' ' + str(self.pk)


class Ligne(models.Model):
    mouvement = models.ForeignKey(Mouvement, on_delete=models.CASCADE, null=True)
    citation = models.CharField(max_length=250, blank=True, null=True)
    outil = models.CharField(max_length=250, blank=True, null=True)
    analyse = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return str(self.mouvement) + str(self.pk)

Presentation/forms.py
# S/O to philgyford : 
# https://github.com/philgyford/django-nested-inline-formsets-example/tree/main/publishing/books


from django.forms import ModelForm, ModelChoiceField, inlineformset_factory, BaseInlineFormSet
from django.utils.translation import gettext_lazy as _

from .models import Texte, Auteur, Mouvement, Ligne
from .utils import RelatedFieldWidgetCanAdd, is_empty_form, is_form_persisted


class AuteurForm(ModelForm):
    class Meta:
        model = Auteur
        fields = '__all__'


"""class TexteForm(ModelForm):
    
    auteur = ModelChoiceField(
       required=False,
       queryset=Auteur.objects.all(),
       widget=RelatedFieldWidgetCanAdd(Auteur, related_url="Presentation:add_author")
                                )

    class Meta:
        model = Texte
        fields = '__all__'"""



# The formset for editing the Ligne that belong to a Mouvement.
LigneFormset = inlineformset_factory(
    Mouvement, Ligne, exclude=('child', ), extra=4
)


class BaseMouvementFormset(BaseInlineFormSet):
    """
    The base formset for editing Mouvements belonging to a Texte, and the
    Ligne belonging to those Mouvements.
    """

    def add_fields(self, form, index):
        super().add_fields(form, index)

        # Save the formset for a Child's Images in the nested property.
        form.nested = LigneFormset(
            instance=form.instance,
            data=form.data if form.is_bound else None,
            files=form.files if form.is_bound else None,
            prefix="Address-%s-%s"
            % (form.prefix, LigneFormset.get_default_prefix()),
        )

    def is_valid(self):
        """
        Also validate the nested formsets.
        """
        result = super().is_valid()

        if self.is_bound:
            for form in self.forms:
                if hasattr(form, "nested"):
                    result = result and form.nested.is_valid()

        return result

    def clean(self):
        """
        If a parent form has no data, but its nested forms do, we should
        return an error, because we can't save the parent.
        For example, if the Mouvement form is empty, but there are Lignes.
        """
        super().clean()

        for form in self.forms:
            if not hasattr(form, "nested") or self._should_delete_form(form):
                continue

            if self._is_adding_nested_inlines_to_empty_form(form):
                form.add_error(
                    field=None,
                    error=_(
                        "Vous êtes en train d'essayer d'ajouter une Ligne à "
                        "un Mouvement qui n'existe pas encore. Veuillez "
                        "ajouter des informations à propos de ce(s) "
                        "Mouvement(s) et remplissez de nouveau les Lignes"
                    ),
                )

    def save(self, commit=True):
        """
        Also save the nested formsets.
        """
        result = super().save(commit=commit)

        for form in self.forms:
            if hasattr(form, "nested"):
                if not self._should_delete_form(form):
                    form.nested.save(commit=commit)

        return result

    def _is_adding_nested_inlines_to_empty_form(self, form):
        """
        Are we trying to add data in nested inlines to a form that has no data?
        e.g. Adding Lignes to a new Mouvement whose data we haven't entered?
        """
        if not hasattr(form, "nested"):
            # A basic form; it has no nested forms to check.
            return False

        if is_form_persisted(form):
            # We're editing (not adding) an existing model.
            return False

        if not is_empty_form(form):
            # The form has errors, or it contains valid data.
            return False

        # All the inline forms that aren't being deleted:
        non_deleted_forms = set(form.nested.forms).difference(
            set(form.nested.deleted_forms)
        )

        # At this point we know that the "form" is empty.
        # In all the inline forms that aren't being deleted, are there any that
        # contain data? Return True if so.
        return any(not is_empty_form(nested_form) for nested_form in non_deleted_forms)


# This is the formset for the Mouvements belonging to a Texte and the
# Lignes belonging to those Mouvements.
#
# You'd use this by passing in a Texte:
#     TexteMouvementFormset(**form_kwargs, instance=self.object)
ChildrenFormset = inlineformset_factory(
    Texte,
    Mouvement,
    formset=BaseMouvementFormset,
    # We need to specify at least one Mouvement field:
    exclude=('parent',),
    extra=3,
    # If you don't want to be able to delete Textes:
    # can_delete=False
)

OralBAC/views.py
from django.shortcuts import render


def main(request):
    return render(request, 'main.html')

Presentation/views.py
# from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect

from .models import Texte
from .filters import TexteFilter
from .forms import AuteurForm


def index(request):
    textes = Texte.objects.order_by("id")
    myFilter = TexteFilter(request.GET, queryset=textes)
    textes = myFilter.qs
    context = {
        'textes' : textes,
        'myFilter' : myFilter
        }
    return render(request, 'Presentation/index.html', context)


def texte(request, key):
    # gérer les erreurs
    texte = get_object_or_404(Texte, url=key)
    context = {
        'texte' : texte,
        'mouvements' : texte.mouvement_set.all()
        }
    return render(request, 'Presentation/texte.html', context)


def add(request):
    texte = get_object_or_404(Texte, title="Vénus Anadyomène")
    return render(request, 'Presentation/add.html')



def add_author(request):

    form = AuteurForm()

    if request.method == 'POST':
        form = AuteurForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('Presentation:index')

    context = {'form' : form}

    return render(request, 'Presentation/add_author.html', context)


"""
postgres://wbkyadcsvbxuxo:c0bc16d253c36491e54421aced963b00f47a953be77985bf31b8b4904334ba6f@ec2-34-201-95-176.compute-1.amazonaws.com:5432/d1vr5hrp4stq7p
postgres://wbkyadcsvbxuxo:c0bc16d253c36491e54421aced963b00f47a953be77985bf31b8b4904334ba6f@ec2-34-201-95-176.compute-1.amazonaws.com:5432/d1vr5hrp4stq7p

"""

OralBAC/templates/OralBAC/main.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Réviser l'oral de français</title>
</head>
<body>
    <a href="{% url 'Presentation:index' %}">Accéder aux textes</a>
</body>
</html>

Presentation/templates/Presentation/add.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un texte</title>
</head>
<body>
    <h1>Ajouter un texte à la base de données</h1>

    <form action="" method="post">
        {% csrf_token %}

        <input type="submit" name="Enregistrer">
    </form>
</body>
</html>

Presentation/templates/Presentation/add_author.html
<!DOCTYPE html>
<html lang="fr'">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un auteur</title>
</head>
<body>
    <h1>Ajouter un auteur à la base de données</h1>
    <br>

    <form action="" method="POST">

        {% csrf_token %}

        <table>{{ form.as_table }}</table>
        <input type="submit" name="Submit">
    </form>
</body>
</html>

Presentation/templates/Presentation/add_mvt.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un mouvement</title>
</head>
<body>

    <form action="" method="POST">

        {% csrf_token %}

        {{ formset.management_form }}
        {% for form in formset %}
            <table>{{ form.as_table }}</table>
            <br>
        {% endfor %}
        <input type="submit" name="Submit">
    </form>
</body>
</html>

Presentation/templates/Presentation/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Rechercher un texte</title>
</head>
<body>
    <div class="filter">
        <form method="get">
            
            {{ myFilter.form }}

            <button class="btn btn-primary" type="submit">Search</button>
        </form>
    </div>
        {% if textes %}
            {% for t in textes%}
                <a href="{% url 'Presentation:texte' t.url %}">{{ t.title }}</a>  
                <br>
                {% endfor %}
        {% else %}
            <p>Aucun texte ne correspond à votre recherche...</p>
        {% endif %}
</body>
</html>

Presentation/templates/Presentation/texte.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ texte.title }}</title>
    <style>
        table,th,td{border:1px solid #cccccc}
    </style>
</head>
<body>
    <div>
        <h1>Introduction</h1>
        <div class="authors_life">
            <p>Naissance : {{ texte.auteur.birth_date | date:"Y" }}</p>
        </div>
        <div class="presentation">
            {{ texte.presentation }}
        </div>
        <div class="lecture">LECTURE</div>
        <div class="mouvements">
            <h3>Mouvements ({{mouvements|length}})</h3>
            <ul>
                {% for m in mouvements %}
                    <li>{{m.range}} : <strong>{{m.title}}</strong></li>
                {% endfor %}
            </ul>
        </div>
        <div class="problematique">
            {{ texte.problematique }}
        </div>
    </div>

    {% for m in mouvements %}
        <div class="mvt {{forloop.counter}}">
            <h1>Mouvement {{forloop.counter}} : {{m.title}} ({{m.range}})</h1>
            <table>
                <tr>
                    <th>Citation</th>
                    <th>Outil</th>
                    <th>Analyse</th>
                </tr>
                {% for l in m.ligne_set.all %}
                    <tr>
                        <td>{{l.citation}}</td>
                        <td>{{l.outil}}</td>
                        <td>{{l.analyse}}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endfor %}

    <div>
        <h1>Conclusion</h1>
        <p>{{texte.texte_conclusion}}</p>
        <p>Ouverture : {{texte.ouverture}}</p>
    </div>
</body>
</html>